### ISSUE TITLE
New Sink: Mattermost

### ISSUE THREAD

**Issue by Mshahidtaj** [robusta-dev/robusta#428] opened 2022-07-12 05:13 UTC
**Is your feature request related to a problem? Please describe.**
During my test spike, i found its hard to configure sink (via webhook) for Mattermost app (Mattermost is an open source tool for team messaging, task and project management, and workflow orchestration.)

**Describe the solution you'd like**
An additional sink destination for Mattermost , similar to the MS teams, Slack etc

**Describe alternatives you've considered**
I tried integrating Robusta with mattermost via web-hook configuration but initial attempt didn't work. 

**Additional context**
Please have a look here: https://mattermost.com

**Comment by arikalon1** [comment] 2022-07-14 08:55
Thanks for reporting it @Mshahidtaj 

We're working on adding Mattermost sink.

I'm closing this issue as duplicate of #263

**Comment by m0sh1x2** [comment] 2022-07-26 06:57
Hello, Quick update on possible future-feature compatibility - the Mattermost Webhooks are Slack compatible which means that any setup that works with Slack Webhooks should work with Mattermost webhooks.

Source - [Mattermost incoming webhooks are Slack-compatible.](https://docs.mattermost.com/developer/webhooks-incoming.html#:~:text=Mattermost%20incoming%20webhooks%20are%20Slack%2Dcompatible.%20You%20can%20copy%2Dand%2Dpaste%20code%20used%20for%20a%20Slack%20incoming%20webhook%20to%20create%20Mattermost%20integrations.%20Mattermost%20automatically%20translates%20the%20Slack%E2%80%99s%20proprietary%20JSON%20payload%20format.)

**Comment by arikalon1** [comment] 2022-07-26 07:05
Thanks for the information @m0sh1x2 
That makes the Mattermost sink a lot easier to build

**Comment by aantn** [comment] 2022-09-01 15:16
Released!

Please provide feedback and let us know once you start using it.

**Closed by aantn** 2022-09-01 15:16 UTC
Labels: sink
