### ISSUE TITLE
Logs enricher when use prometheus does not show the graph for node utilisation

### ISSUE THREAD

**Issue by antikilahdjs** [robusta-dev/robusta#1168] opened 2023-11-14 20:27 UTC
**Describe the bug**

Hey, I am using the Robusta some days ago with Prometheus plus Alertmanager but the enricher for prometheus like memory or cpu is empty when fired to teams as alert. Only the graph for memory usage appears in the graph but the node utilisation is not showing.

The image below will demonstrate it 

![image](https://github.com/robusta-dev/robusta/assets/33559260/7e86808f-3e34-4c81-ba88-303ac5f1620a)

**To Reproduce**
1 - Install using the official helm charts
3 - Configure Prometheus and  Alertmanager
4 - Configure the SINK to use Teams
5 - In my global env has been configured like below 
```yaml
globalConfig:
  grafana_url: ""
  grafana_api_key: ""
  grafana_dashboard_uid: ""
  alertmanager_url: "http://alertmanager-operated.thanos:9093"
  prometheus_url: "http://thanos-query-frontend.thanos:9090"
  signing_key: ""
  account_id: 695c3053-0e56-xxxxxxxxxxxxxxxxxxxxxx
  custom_annotations: []
```

5 - My trigger and action is:
```yaml
- triggers:
  - on_pod_oom_killed:
      rate_limit: 3600
  actions:
  - pod_oom_killer_enricher: {}
  - logs_enricher: {}
  - pod_node_graph_enricher:
      resource_type: Memory
      display_limits: true
  - oomkilled_container_graph_enricher:
      resource_type: Memory
      display_limits: true
  stop: true
```

**Expected behavior**

The graph woks for both sides, node utilisation and pod utilisation

**Screenshots**
It was added above

**Desktop (please complete the following information):**
 - OS: RedHat 8.5 and Ubunut 20.04LTS
 - Browser: Chrome
 - Version: 119

**Additional context**

**Comment by saireddyb** [comment] 2023-11-24 04:23
Yes I to receive the node graph empty.

**Comment by wrbbz** [comment] 2024-05-16 08:49
Same here on Robusta 0.12.0 without UI integration

**Comment by arikalon1** [comment] 2024-05-16 15:53
@Bobses @wrbbz do you see any exception in the robusta-runner pod logs ?

**Comment by aantn** [comment] 2024-05-17 11:21
Hi all, I believe this is because robusta is using the recording rule `instance:node_memory_utilisation:ratio` which isn't present in your environment.

[source code here](https://github.com/robusta-dev/robusta/blob/63f24a03f0d6b14ea97000955f0b5fec331adcc8/src/robusta/core/playbooks/prometheus_enrichment_utils.py#L485)

If that is the case, we should be able to fix this by replacing the with [it's definition](https://github.com/prometheus/node_exporter/blob/3afc0a341e3c2c6605b18a882fb045318c18c444/docs/node-mixin/rules/rules.libsonnet#L41): or possibly just by 
 `container_memory_working_set_bytes{node="${node_name}", container!=""}`

**Comment by aantn** [comment] 2024-05-17 11:22
To help us get to the bottom of this, can each of you please verify that the metric `instance:node_memory_utilisation:ratio` is in fact missing from your environment.

**Comment by wrbbz** [comment] 2024-05-17 15:13
Yeah. I can confirm that we do not have `instance:node_memory_utilisation:ratio`. Only `container_memory_working_set_bytes`

**Comment by Bobses** [comment] 2024-05-20 09:02
I confirm that we don't have that record.

So, I'll add the following record:
```
record: instance:node_memory_utilisation:ratio
expr: 1 - (node_memory_MemAvailable_bytes{job="node-exporter"} or (node_memory_Buffers_bytes{job="node-exporter"} + node_memory_Cached_bytes{job="node-exporter"} + node_memory_MemFree_bytes{job="node-exporter"} + node_memory_Slab_bytes{job="node-exporter"} ) / node_memory_MemTotal_bytes{job="node-exporter"}) 
```

Thank you!

**Comment by aantn** [comment] 2024-05-20 09:04
Yep, that will fix the problem. (Please confirm!)

I think we should also change this on our side to query the expr instead and not rely on that recording rule.

**Comment by wrbbz** [comment] 2024-05-21 10:37
I've created a PR on usage definitions instead of records

Also, adding record to the Prom instance solved No Data error

**Comment by aantn** [comment] 2024-06-15 19:27
@wrbbz thank you for the fix. It will be included in the next Robusta release!

**Closed by aantn** 2024-06-15 19:27 UTC
Labels: needs-triage
