### ISSUE TITLE
check_prometheus_connection ignores prometheus_auth

### ISSUE THREAD

**Issue by djfinnoy** [robusta-dev/robusta#915] opened 2023-05-30 16:08 UTC
**Describe the bug**
When attempting to connect Robusta to a local Prometheus instance with basic auth enabled, I get the following errors in the runner logs:

```
ERROR    Failed to connect to prometheus. Couldn't connect to Prometheus found under http://prometheus-frontend.monitoring.svc.cluster.local

Caused by HTTPError: 401 Client Error: Unauthorized for url: http://prometheus-frontend.monitoring.svc.cluster.local/api/v1/query?query=example)

Traceback (most recent call last):
  File "/app/src/robusta/integrations/prometheus/utils.py", line 108, in check_prometheus_connection
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://prometheus-frontend.monitoring.svc.cluster.local/api/v1/query?query=example

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/src/robusta/core/sinks/robusta/robusta_sink.py", line 340, in __update_cluster_status
    check_prometheus_connection(prom=prometheus_connection, params={})
  File "/app/src/robusta/integrations/prometheus/utils.py", line 110, in check_prometheus_connection
    raise PrometheusNotFound(
robusta.core.exceptions.PrometheusNotFound: Couldn't connect to Prometheus found under http://prometheus-frontend.monitoring.svc.cluster.local
Caused by HTTPError: 401 Client Error: Unauthorized for url: http://prometheus-frontend.monitoring.svc.cluster.local/api/v1/query?query=example)
```

Here is an excerpt from my Helm configuration:

```
  globalConfig:
    signing_key: "{{ env.SIGNING_KEY }}"
    account_id: "{{ env.ACCOUNT_ID }}"
    prometheus_url: "http://prometheus-frontend.monitoring.svc.cluster.local"
    prometheus_auth: "Basic <correct base64 encoded-string>"
```

I have verified that the `prometheus_auth` field is correct within `robusta-playbooks-config-secret`.
It is the exact same base64 string that I see when inspecting headers for Prometheus in my browser.
I suspect that the Prometheus integration is actually working (I am no longer seeing warnings related to a faulty Prometheus connection in the Robusta UI, I think these disappeared after I configured Robusta to include the basic auth header).

Based on my limited understanding of Robusta and Python, I think the error is caused by [this function](https://github.com/robusta-dev/robusta/blob/6cd4f3b38ad5c5dc14bc93c04348c178bc762898/src/robusta/core/sinks/robusta/prometheus_health_checker.py#LL54C79-L54C79) not being configured to use the `prometheus_auth` parameter from `globalConfig`. If I am interpreting the log message above correctly, there auth parameters were not included in this function call: `check_prometheus_connection(prom=prometheus_connection, params={})`

**To Reproduce**
1. Activate basic auth for a Prometheus instance running in the same cluster as Robusta
2. Attempt to establish a connection between Robusta and Prometheus via `globalConfig.prometheus_auth`.
3. Check logs from robusta-runner

**Expected behavior**
The `__update_cluster_status` function should not throw errors when Prometheus is protected with basic auth.

**Additional context**
I am new to Robusta, and I only noticed this error because I was looking for a way to verify that the Prometheus + basic auth connection was working. At the moment, I am not sure if this is the case; the only indications I have to go by are the errors in the log, and the lack of errors in the UI. Perhaps there should be a health monitor for the Prometheus connection within the UI somewhere.

**Comment by arikalon1** [comment] 2023-05-30 16:22
Thanks for reporting this @djfinnoy 
I think this was fixed as a part of this [commit](https://github.com/robusta-dev/robusta/commit/ed7e97c5dd59e044a87af1f836b53b5e7f8df7cf)

It's going to be released in the next few days

**Comment by djfinnoy** [comment] 2023-05-30 18:00
Excellent, thank you for the quick response. I look forward to rolling out the new version. If there are any pre-release Helm charts / containers available I would be happy to test it and see if it resolves the issue on our end.

**Comment by arikalon1** [comment] 2023-05-30 18:27
This is the pre-release for the coming version:
https://github.com/robusta-dev/robusta/releases/tag/0.10.17-alpha.4

Can you please test if the issue is resolved when using this version?

**Comment by arikalon1** [comment] 2023-05-31 07:43
Thanks @djfinnoy 
Failing to fetch the flags shouldn't effect the prometheus connection.
We need to convert the log to warning.

Does prometheus queries work for you with this version?
Which prometheus distribution are you using?

**Comment by djfinnoy** [comment] 2023-05-31 07:45
Prometheus queries work fine. It is a Google Managed Prometheus instance, and we deploy the frontend ourselves in order to provide our Cloud Grafana (not self-hosted) with an endpoint to query. This works.

Like I said in the original post: I suspect that the Robusta <-> Prometheus integration is actually working, and that these error messages are just noise. Are there any easy ways to test this hypothesis?

**Comment by arikalon1** [comment] 2023-05-31 07:49
I think you're right.
We try to fetch the prometheus flags, to get the retention period.
This is optional, so the failure to get the flags doesn't have a major effect (we won't be able to tell you, the query exceeded the retention period)

We need to find a solution where we don't spam the logs with that

**Comment by djfinnoy** [comment] 2023-05-31 07:51
Good stuff. But I am still very interested in some sort of Prometheus health check in the UI, or a CLI command to verify that the Prometheus integration is working. Right now, I'm not sure, and I am not familiar enough with Robusta to verify that everything is alright.

**Comment by arikalon1** [comment] 2023-05-31 08:29
We're adding a clusters page, in which there will be a status indication, including prometheus connectivity.

For now, the best way to verify prometheus is working properly, is to go into an application details page, and verify the memory and cpu utilization graphs are available

**Comment by djfinnoy** [comment] 2023-05-31 09:30
Sounds good. I can confirm that the memory and CPU util graphs are working, hopefully the error messages will get fixed / have lower severity in a future release.

Feel free to close the issue, unless you want to leave it open to target the log errors.

**Comment by djfinnoy** [comment] 2023-05-31 18:01
Sure, I'll see if I can get around to it over the next couple of weeks.

**Closed** 2023-06-04 23:03 UTC
